# coding: utf-8

"""
    MailOdds Email Validation API

    MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 

    The version of the OpenAPI document: 1.0.0
    Contact: support@mailodds.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mailodds.api.validation_policies_api import ValidationPoliciesApi


class TestValidationPoliciesApi(unittest.TestCase):
    """ValidationPoliciesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ValidationPoliciesApi()

    def tearDown(self) -> None:
        pass

    def test_add_policy_rule(self) -> None:
        """Test case for add_policy_rule

        Add rule to policy
        """
        pass

    def test_create_policy(self) -> None:
        """Test case for create_policy

        Create policy
        """
        pass

    def test_create_policy_from_preset(self) -> None:
        """Test case for create_policy_from_preset

        Create policy from preset
        """
        pass

    def test_delete_policy(self) -> None:
        """Test case for delete_policy

        Delete policy
        """
        pass

    def test_delete_policy_rule(self) -> None:
        """Test case for delete_policy_rule

        Delete rule
        """
        pass

    def test_get_policy(self) -> None:
        """Test case for get_policy

        Get policy
        """
        pass

    def test_get_policy_presets(self) -> None:
        """Test case for get_policy_presets

        Get policy presets
        """
        pass

    def test_list_policies(self) -> None:
        """Test case for list_policies

        List policies
        """
        pass

    def test_test_policy(self) -> None:
        """Test case for test_policy

        Test policy evaluation
        """
        pass

    def test_update_policy(self) -> None:
        """Test case for update_policy

        Update policy
        """
        pass


if __name__ == '__main__':
    unittest.main()
