# coding: utf-8

"""
    MailOdds Email Validation API

    MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 

    The version of the OpenAPI document: 1.0.0
    Contact: support@mailodds.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mailodds.models.policy_presets_response_presets_inner import PolicyPresetsResponsePresetsInner

class TestPolicyPresetsResponsePresetsInner(unittest.TestCase):
    """PolicyPresetsResponsePresetsInner unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PolicyPresetsResponsePresetsInner:
        """Test PolicyPresetsResponsePresetsInner
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PolicyPresetsResponsePresetsInner`
        """
        model = PolicyPresetsResponsePresetsInner()
        if include_optional:
            return PolicyPresetsResponsePresetsInner(
                id = '',
                name = '',
                description = '',
                rules = [
                    mailodds.models.policy_rule.PolicyRule(
                        id = 56, 
                        type = 'status_override', 
                        condition = mailodds.models.condition.condition(), 
                        action = mailodds.models.policy_rule_action.PolicyRule_action(), 
                        sequence = 56, 
                        is_enabled = True, )
                    ]
            )
        else:
            return PolicyPresetsResponsePresetsInner(
        )
        """

    def testPolicyPresetsResponsePresetsInner(self):
        """Test PolicyPresetsResponsePresetsInner"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
