# coding: utf-8

"""
    MailOdds Email Validation API

    MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 

    The version of the OpenAPI document: 1.0.0
    Contact: support@mailodds.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mailodds.api.sending_domains_api import SendingDomainsApi


class TestSendingDomainsApi(unittest.TestCase):
    """SendingDomainsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = SendingDomainsApi()

    def tearDown(self) -> None:
        pass

    def test_create_sending_domain(self) -> None:
        """Test case for create_sending_domain

        Add a sending domain
        """
        pass

    def test_delete_sending_domain(self) -> None:
        """Test case for delete_sending_domain

        Delete a sending domain
        """
        pass

    def test_get_sending_domain(self) -> None:
        """Test case for get_sending_domain

        Get a sending domain
        """
        pass

    def test_get_sending_domain_identity_score(self) -> None:
        """Test case for get_sending_domain_identity_score

        Get domain identity score
        """
        pass

    def test_get_sending_stats(self) -> None:
        """Test case for get_sending_stats

        Get sending statistics
        """
        pass

    def test_list_sending_domains(self) -> None:
        """Test case for list_sending_domains

        List sending domains
        """
        pass

    def test_verify_sending_domain(self) -> None:
        """Test case for verify_sending_domain

        Verify domain DNS records
        """
        pass


if __name__ == '__main__':
    unittest.main()
