# coding: utf-8

"""
    MailOdds Email Validation API

    MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 

    The version of the OpenAPI document: 1.0.0
    Contact: support@mailodds.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from mailodds.api.email_validation_api import EmailValidationApi


class TestEmailValidationApi(unittest.TestCase):
    """EmailValidationApi unit test stubs"""

    def setUp(self) -> None:
        self.api = EmailValidationApi()

    def tearDown(self) -> None:
        pass

    def test_validate_batch(self) -> None:
        """Test case for validate_batch

        Validate multiple emails (sync)
        """
        pass

    def test_validate_email(self) -> None:
        """Test case for validate_email

        Validate single email
        """
        pass


if __name__ == '__main__':
    unittest.main()
