# flake8: noqa

# import apis into api package
from mailodds.api.agent_control_plane_api import AgentControlPlaneApi
from mailodds.api.alert_rules_api import AlertRulesApi
from mailodds.api.blacklist_monitoring_api import BlacklistMonitoringApi
from mailodds.api.bounce_analysis_api import BounceAnalysisApi
from mailodds.api.bulk_validation_api import BulkValidationApi
from mailodds.api.campaign_analytics_api import CampaignAnalyticsApi
from mailodds.api.campaigns_api import CampaignsApi
from mailodds.api.configuration_sets_api import ConfigurationSetsApi
from mailodds.api.contact_lists_api import ContactListsApi
from mailodds.api.content_classification_api import ContentClassificationApi
from mailodds.api.dkim_management_api import DKIMManagementApi
from mailodds.api.dmarc_monitoring_api import DMARCMonitoringApi
from mailodds.api.deliverability_advisor_api import DeliverabilityAdvisorApi
from mailodds.api.domain_insights_api import DomainInsightsApi
from mailodds.api.email_sending_api import EmailSendingApi
from mailodds.api.email_validation_api import EmailValidationApi
from mailodds.api.engagement_api import EngagementApi
from mailodds.api.event_destinations_api import EventDestinationsApi
from mailodds.api.events_api import EventsApi
from mailodds.api.global_suppressions_api import GlobalSuppressionsApi
from mailodds.api.ispfbl_guides_api import ISPFBLGuidesApi
from mailodds.api.inbound_processing_api import InboundProcessingApi
from mailodds.api.inbound_rules_api import InboundRulesApi
from mailodds.api.managed_spf_api import ManagedSPFApi
from mailodds.api.message_events_api import MessageEventsApi
from mailodds.api.o_auth20_api import OAuth20Api
from mailodds.api.out_of_office_api import OutOfOfficeApi
from mailodds.api.pipeline_simulation_api import PipelineSimulationApi
from mailodds.api.pixel_settings_api import PixelSettingsApi
from mailodds.api.reputation_api import ReputationApi
from mailodds.api.reputation_policies_api import ReputationPoliciesApi
from mailodds.api.sender_health_api import SenderHealthApi
from mailodds.api.sending_delegations_api import SendingDelegationsApi
from mailodds.api.sending_domains_api import SendingDomainsApi
from mailodds.api.server_tests_api import ServerTestsApi
from mailodds.api.spam_checks_api import SpamChecksApi
from mailodds.api.subscriber_lists_api import SubscriberListsApi
from mailodds.api.suppression_lists_api import SuppressionListsApi
from mailodds.api.system_api import SystemApi
from mailodds.api.template_versions_api import TemplateVersionsApi
from mailodds.api.validation_policies_api import ValidationPoliciesApi
from mailodds.api.webhook_cli_api import WebhookCLIApi

