# coding: utf-8

"""
    MailOdds Email Validation API

    MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 

    The version of the OpenAPI document: 1.0.0
    Contact: support@mailodds.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from mailodds.models.deliver_request_options import DeliverRequestOptions
from mailodds.models.deliver_request_structured_data import DeliverRequestStructuredData
from mailodds.models.deliver_request_to_inner import DeliverRequestToInner
from typing import Optional, Set
from typing_extensions import Self

class DeliverRequest(BaseModel):
    """
    DeliverRequest
    """ # noqa: E501
    to: List[DeliverRequestToInner] = Field(description="List of recipient email addresses")
    var_from: StrictStr = Field(description="Sender email address (must match sending domain)", alias="from")
    subject: StrictStr = Field(description="Email subject line")
    html: Optional[StrictStr] = Field(default=None, description="HTML email body")
    text: Optional[StrictStr] = Field(default=None, description="Plain text email body")
    domain_id: StrictStr = Field(description="Sending domain UUID")
    reply_to: Optional[StrictStr] = Field(default=None, description="Reply-to address")
    headers: Optional[Dict[str, Any]] = Field(default=None, description="Extra email headers")
    tags: Optional[List[StrictStr]] = Field(default=None, description="Tags for categorization")
    campaign_type: Optional[StrictStr] = Field(default=None, description="Campaign type for JSON-LD auto-generation")
    structured_data: Optional[DeliverRequestStructuredData] = None
    options: Optional[DeliverRequestOptions] = None
    __properties: ClassVar[List[str]] = ["to", "from", "subject", "html", "text", "domain_id", "reply_to", "headers", "tags", "campaign_type", "structured_data", "options"]

    @field_validator('campaign_type')
    def campaign_type_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['order_confirmation', 'shipping_notification', 'subscription_confirm', 'review_request', 'event_invitation', 'promotional', 'welcome', 'password_reset', 'appointment_reminder', 'ticket_confirmation']):
            raise ValueError("must be one of enum values ('order_confirmation', 'shipping_notification', 'subscription_confirm', 'review_request', 'event_invitation', 'promotional', 'welcome', 'password_reset', 'appointment_reminder', 'ticket_confirmation')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of DeliverRequest from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in to (list)
        _items = []
        if self.to:
            for _item_to in self.to:
                if _item_to:
                    _items.append(_item_to.to_dict())
            _dict['to'] = _items
        # override the default output from pydantic by calling `to_dict()` of structured_data
        if self.structured_data:
            _dict['structured_data'] = self.structured_data.to_dict()
        # override the default output from pydantic by calling `to_dict()` of options
        if self.options:
            _dict['options'] = self.options.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of DeliverRequest from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "to": [DeliverRequestToInner.from_dict(_item) for _item in obj["to"]] if obj.get("to") is not None else None,
            "from": obj.get("from"),
            "subject": obj.get("subject"),
            "html": obj.get("html"),
            "text": obj.get("text"),
            "domain_id": obj.get("domain_id"),
            "reply_to": obj.get("reply_to"),
            "headers": obj.get("headers"),
            "tags": obj.get("tags"),
            "campaign_type": obj.get("campaign_type"),
            "structured_data": DeliverRequestStructuredData.from_dict(obj["structured_data"]) if obj.get("structured_data") is not None else None,
            "options": DeliverRequestOptions.from_dict(obj["options"]) if obj.get("options") is not None else None
        })
        return _obj


