# coding: utf-8

"""
    MailOdds Email Validation API

    MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 

    The version of the OpenAPI document: 1.0.0
    Contact: support@mailodds.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from mailodds.models.telemetry_summary_rates import TelemetrySummaryRates
from mailodds.models.telemetry_summary_top_domains_inner import TelemetrySummaryTopDomainsInner
from mailodds.models.telemetry_summary_top_reasons_inner import TelemetrySummaryTopReasonsInner
from mailodds.models.telemetry_summary_totals import TelemetrySummaryTotals
from typing import Optional, Set
from typing_extensions import Self

class TelemetrySummary(BaseModel):
    """
    Validation metrics for building dashboards and monitoring.
    """ # noqa: E501
    schema_version: Optional[StrictStr] = Field(default=None, alias="schemaVersion")
    window: Optional[StrictStr] = None
    generated_at: Optional[datetime] = Field(default=None, alias="generatedAt")
    timezone: Optional[StrictStr] = None
    totals: Optional[TelemetrySummaryTotals] = None
    rates: Optional[TelemetrySummaryRates] = None
    top_reasons: Optional[List[TelemetrySummaryTopReasonsInner]] = Field(default=None, description="Top rejection/status reasons", alias="topReasons")
    top_domains: Optional[List[TelemetrySummaryTopDomainsInner]] = Field(default=None, description="Top domains by volume", alias="topDomains")
    __properties: ClassVar[List[str]] = ["schemaVersion", "window", "generatedAt", "timezone", "totals", "rates", "topReasons", "topDomains"]

    @field_validator('window')
    def window_validate_enum(cls, value):
        """Validates the enum"""
        if value is None:
            return value

        if value not in set(['1h', '24h', '30d']):
            raise ValueError("must be one of enum values ('1h', '24h', '30d')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TelemetrySummary from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of totals
        if self.totals:
            _dict['totals'] = self.totals.to_dict()
        # override the default output from pydantic by calling `to_dict()` of rates
        if self.rates:
            _dict['rates'] = self.rates.to_dict()
        # override the default output from pydantic by calling `to_dict()` of each item in top_reasons (list)
        _items = []
        if self.top_reasons:
            for _item_top_reasons in self.top_reasons:
                if _item_top_reasons:
                    _items.append(_item_top_reasons.to_dict())
            _dict['topReasons'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in top_domains (list)
        _items = []
        if self.top_domains:
            for _item_top_domains in self.top_domains:
                if _item_top_domains:
                    _items.append(_item_top_domains.to_dict())
            _dict['topDomains'] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TelemetrySummary from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "schemaVersion": obj.get("schemaVersion"),
            "window": obj.get("window"),
            "generatedAt": obj.get("generatedAt"),
            "timezone": obj.get("timezone"),
            "totals": TelemetrySummaryTotals.from_dict(obj["totals"]) if obj.get("totals") is not None else None,
            "rates": TelemetrySummaryRates.from_dict(obj["rates"]) if obj.get("rates") is not None else None,
            "topReasons": [TelemetrySummaryTopReasonsInner.from_dict(_item) for _item in obj["topReasons"]] if obj.get("topReasons") is not None else None,
            "topDomains": [TelemetrySummaryTopDomainsInner.from_dict(_item) for _item in obj["topDomains"]] if obj.get("topDomains") is not None else None
        })
        return _obj


