# coding: utf-8

"""
    MailOdds Email Validation API

    MailOdds provides email validation services to help maintain clean email lists  and improve deliverability. The API performs multiple validation checks including  format verification, domain validation, MX record checking, and disposable email detection.  ## Authentication  All API requests require authentication using a Bearer token. Include your API key  in the Authorization header:  ``` Authorization: Bearer YOUR_API_KEY ```  API keys can be created in the MailOdds dashboard.  ## Rate Limits  Rate limits vary by plan: - Free: 10 requests/minute - Starter: 60 requests/minute   - Pro: 300 requests/minute - Business: 1000 requests/minute - Enterprise: Custom limits  ## Response Format  All responses include: - `schema_version`: API schema version (currently \"1.0\") - `request_id`: Unique request identifier for debugging  Error responses include: - `error`: Machine-readable error code - `message`: Human-readable error description 

    The version of the OpenAPI document: 1.0.0
    Contact: support@mailodds.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr, field_validator
from typing import Any, ClassVar, Dict, List, Optional
from mailodds.models.validation_response_suppression_match import ValidationResponseSuppressionMatch
from typing import Optional, Set
from typing_extensions import Self

class ValidationResponse(BaseModel):
    """
    ValidationResponse
    """ # noqa: E501
    schema_version: Optional[StrictStr] = None
    email: StrictStr
    status: StrictStr = Field(description="Validation status")
    sub_status: Optional[StrictStr] = Field(default=None, description="Detailed status reason")
    action: StrictStr = Field(description="Recommended action")
    domain: Optional[StrictStr] = None
    mx_found: Optional[StrictBool] = None
    smtp_check: Optional[StrictBool] = None
    disposable: Optional[StrictBool] = None
    role_account: Optional[StrictBool] = None
    free_provider: Optional[StrictBool] = None
    suppression_match: Optional[ValidationResponseSuppressionMatch] = None
    __properties: ClassVar[List[str]] = ["schema_version", "email", "status", "sub_status", "action", "domain", "mx_found", "smtp_check", "disposable", "role_account", "free_provider", "suppression_match"]

    @field_validator('status')
    def status_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['valid', 'invalid', 'catch_all', 'do_not_mail', 'unknown']):
            raise ValueError("must be one of enum values ('valid', 'invalid', 'catch_all', 'do_not_mail', 'unknown')")
        return value

    @field_validator('action')
    def action_validate_enum(cls, value):
        """Validates the enum"""
        if value not in set(['accept', 'accept_with_caution', 'reject', 'retry_later']):
            raise ValueError("must be one of enum values ('accept', 'accept_with_caution', 'reject', 'retry_later')")
        return value

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ValidationResponse from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of suppression_match
        if self.suppression_match:
            _dict['suppression_match'] = self.suppression_match.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ValidationResponse from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "schema_version": obj.get("schema_version"),
            "email": obj.get("email"),
            "status": obj.get("status"),
            "sub_status": obj.get("sub_status"),
            "action": obj.get("action"),
            "domain": obj.get("domain"),
            "mx_found": obj.get("mx_found"),
            "smtp_check": obj.get("smtp_check"),
            "disposable": obj.get("disposable"),
            "role_account": obj.get("role_account"),
            "free_provider": obj.get("free_provider"),
            "suppression_match": ValidationResponseSuppressionMatch.from_dict(obj["suppression_match"]) if obj.get("suppression_match") is not None else None
        })
        return _obj


